### ISSUE TITLE
Spatial misalignment between RGB and Depth frames

### ISSUE THREAD

**Issue by goutamyg** [amrgomaaelhady/SynthoGestures#4]
Hi,

I exported the RGB and Depth camera captures as jpg files using UE's Sequencer at 30fps. When I overlay the frames from both streams, I could see that there is a strong spatial misalignment between them, as show below. 

![30fps](https://github.com/amrgomaaelhady/SynthoGestures/assets/15650213/481af39a-59f4-4969-a937-6124548f9daa)

I have checked the location and orientation of active RGB and Depth cameras under ```SettingsActor``` and they are matching (otherwise, misalignments will be visible in the seat area, mannequin body etc). 

Interestingly, as I increase the frame rate for rendering, the extent of misalignment reduces. I am aware that the gesture recognition model should be robust to such misalignments, however, I am curious to know if this issue is caused due to some limitations of the UE Sequencer Renderer, or is it due to the code that generates RGB and depth data. Can you please share your thoughts on this?

**Comment by amrgomaaelhady** [comment]
I did not use the UE Sequencer before so I am not sure about its limitation, I know that you need 30 fps to match most datasets out there such as the Nvidia one, but maybe increasing the fps during rendering, then down sampling it externally might be already a good solution as you mentioned. However, there is one more thing you could check. Since I was generating the gestures sequentially, and I introduced different variations to act as noise/different user behavior, are you sure that the generated gestures are exactly the same for both cameras and no variation range is added that might already cause the misalignment (even though the start and end position of the gesture in the same). Maybe check that all hand, arm, and finger variations we previously discussed are set to an exact (same) value without any variability and see if the behavior is the same then. Unless you modified the code to capture the gesture from two camera sources in parallel, then this doesn't apply to you.

**Comment by goutamyg** [comment]
I thought the hand, arm, and finger variation parameter values for each gesture in ```World Outliner``` (e.g., the one below)

![image](https://github.com/amrgomaaelhady/SynthoGestures/assets/15650213/d1c7665e-e3f4-43fd-a9c7-b1c6ac75f6eb) 

are applied to both RGB and Depth cameras in parallel. Also, at 240/480fps, the alignment is much better with the same gesture settings.

**Comment by amrgomaaelhady** [comment]
Yes, they are applied the same for both cameras, but I am not sure if they are loaded once and applied in parallel threads to all Cameras, or they are reinitialized every time when a new "Camera Animation" is played. This would relate more to how UE handle these threads. I think the best way to test that would be to disable all variation ranges and test at low fps to see if the problem persist or not.

**Comment by goutamyg** [comment]
Sure, I will do that. Thank you.

**Comment by amrgomaaelhady** [comment]
Great! Thanks a lot! Let me know how did it work for you if that is okay, I would be interested in knowing that.

**Comment by goutamyg** [comment]
Hi, I de-activated all the randomness associated with one the gestures and exported the video multiple times. The rgb frames across two instances exactly overlap since there is no randomness. However, the rgb-depth streams remain un-aligned.  

My theory is (as someone with almost no knowledge of UE Sequencer's internal mechanism :)), the Sequencer uniformly samples frames along rgb and depth videos (as indicated by arrows below)

![IMG_20240708_131351335 (1)](https://github.com/amrgomaaelhady/SynthoGestures/assets/15650213/fc799717-c0e1-4403-99d0-08bd525894d1)

At low frame rate (i.e., 30fps), the first sample in RGB may not correspond to the first frame in depth video, as shown above. As we increase the frame rate, we get better alignment as the arrows get denser.

**Comment by amrgomaaelhady** [comment]
Hi, thanks a lot for reporting your findings, that is really useful, and I think it will be useful for others. I am not an expert on how UE sequences works as well, but I believe your interpretations makes sense. I believe the solution of increasing the fps (and downsample it externally is the best you can do now). Otherwise, you could also try to capture the frames manually at fixed intervals, but that also comes with some drawbacks such as not having a video form of the data among other things (this [answer ](https://stackoverflow.com/questions/70279294/unreal-engine-taking-screenshots-automatically) on stackoverflow seems to have summed it up).
